openapi: 3.0.0
info:
  title: Zip Code Location Simulator API
  version: 1.0.0
  description: API to retrieve location data based on zip codes.
servers:
  - url: https://et-dreamhouse-agentforce-fac4c0e681a0.herokuapp.com
paths:
  /:
    get:
      summary: Root endpoint, provides a simple HTML page.
      responses:
        "200":
          description: A simple HTML page with a link to the zip code endpoint.
          content:
            text/html:
              schema:
                type: string
  /zip/{zipcode}:
    get:
      summary: Retrieve location data for a specific or random zip code.
      parameters:
        - name: zipcode
          in: path
          required: true
          description: The zip code to retrieve data for.
          schema:
            type: string
      responses:
        "200":
          description: Successful response with zip code data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  city:
                    type: string
                    description: The city associated with the zip code.
                  state:
                    type: string
                    description: The state associated with the zip code.
                  population:
                    type: integer
                    description: The population of the zip code area.
                  latitude:
                    type: number
                    format: float
                    description: The latitude of the zip code area.
                  longitude:
                    type: number
                    format: float
                    description: The longitude of the zip code area.
        "500":
          description: Internal server error.
          content:
            text/plain:
              schema:
                type: string
